### ISSUE TITLE
使用时出现的几个问题与疑问

### ISSUE THREAD

**Issue by zqfzqf** [chenxuuu/Mail-Box-Net-Disk#1]
**系统：** win10_1706_64位

**软件：** v1.0.2.1、win-x64版本

**邮箱：** QQ邮箱，英文邮箱地址

### 问题一：分块大小

​	QQ邮箱的附件大小限制是50mb，我设置的分块大小为45mb，上传文件时：

![](https://i.loli.net/2019/02/21/5c6d932275bbb.png)

​	分块大小设置为30mb没有报错

### 问题二：上传不连续

​	上传时上传完一个分块时，有几率不进行下一个分块的上传，我是通过实时网络流量速度判断的它的上传完毕，此时等很久都不会上传下一个块，但是我点一下powershell窗口内，或者回车一下，有几率恢复正常。

### 问题三：上传时文件夹突然消失

​	我创建一个文件夹，用-lf命令能读取到这个文件夹，往里面上传一个大小约200兆的图片或约300兆的视频进行测试，在上传约2-3个块之后，会报错，说我文件夹找不到了，此时Ctrl^C终止后再用-lf命令，文件夹确实消失，但在QQ邮箱的网站上还有，里面已经上传的文件几个分块也在。

![](https://i.loli.net/2019/02/21/5c6d963517466.png)

​	因为这个问题，我没能成功使用过这个程序。

### 问题四：配置疑问

​	配置里的account是邮箱地址吗，和address有什么区别？

以上是我使用最新版本程序的几个问题，希望得到解答，同时感谢作者做出这么好的软件。

**Comment by chenxuuu** [comment]
1. 按邮件标准，附件在邮件中是以base64编码的，而腾讯服务器判定是依据邮件大小，即实际大小约等于文件大小*4/3+其他字符

2. 没有遇到过，只有服务器对上传文件进行处理时，会等服务器返回成功的回复

3. 不完整的文件会作为无效文件，可以用-c参数清理

4. 这是遗留问题，当初计划用smtp发件，所以需要一个收件地址。现在不需要了，只需要account

**Comment by chenxuuu** [comment]
1. 按邮件标准，附件在邮件中是以base64编码的，而腾讯服务器判定是依据邮件大小，即实际大小约等于文件大小*4/3+其他字符

2. 没有遇到过，只有服务器对上传文件进行处理时，会等服务器返回成功的回复

3. 不完整的文件会作为无效文件，可以用-c参数清理

4. 这是遗留问题，当初计划用smtp发件，所以需要一个收件地址。现在不需要了，只需要account

**Comment by chenxuuu** [comment]
1. 按邮件标准，附件在邮件中是以base64编码的，而腾讯服务器判定是依据邮件大小，即实际大小约等于文件大小*4/3+其他字符

2. 没有遇到过，只有服务器对上传文件进行处理时，会等服务器返回成功的回复

3. 不完整的文件会作为无效文件，可以用-c参数清理

4. 这是遗留问题，当初计划用smtp发件，所以需要一个收件地址。现在不需要了，只需要account

**Comment by zqfzqf** [comment]
emmm其他问题懂了，主要是问题三，不是文件不完整的问题，这个问题我测试时是100%出现的，emmm如果60mb以内的文件就没问题，因为是在2-3个分卷才出问题，60mb以内出问题前就上传成功了，这就是说如果我上传一个大于60mb的文件时100%不能上传，而且以后这个文件夹也永远读取不到，我只能在邮箱网页端手动删除文件夹，才能再次使用这个软件。
也就是说我在测试时大于60mb的文件时不能上传，会报错，是100%出现报错。

**Comment by chenxuuu** [comment]
文件夹存不存在是qq邮箱决定的，可能他们限制了吧，这里的报错是他们服务器返回的错误，我这里不可能解决的，要去问qq邮箱客服（前提是你能找得到）

**Comment by zqfzqf** [comment]
是这样啊，哪我试试别的邮箱
